// Edad real (Transfermarkt) de los starPlayers de Colombia y Argentina.
//
// Generado por scripts/scrape_kader_tm.mjs, que baja el plantel completo desde
// /kader/verein/<id> de 91 clubes (36 colombianos: Dimayor I + Torneo/B; 55
// argentinos: Clausura + Primera Nacional), y despues cruza por nombre contra
// los starPlayers de ULTIMATE_CLUBS_DATABASE.
//
// Clave: "clubId|nombreTalCualEnStarPlayers" -- mismo formato que
// PLAYER_ENRICHMENT (ver playerEnrichment.ts), para consultarse con la misma
// llave. Cubre 557 de 923 starPlayers de esas dos ligas (60%).
//
// PURAMENTE ADITIVO: no reescribe ULTIMATE_CLUBS_DATABASE ni toca los escudos.
// Los starPlayers de data.ts quedan exactamente como estaban.
//
// Sobre la fiabilidad del cruce (asignar la edad de otra persona es peor que
// quedarse sin edad):
//  - Se exige que coincidan nombre de pila Y apellido. Solo el apellido cruza
//    personas distintas ("Luis Diaz" vs "Yesid Diaz", "Adrian Parra" vs "Neider
//    Parra"); un token cualquiera es peor aun ("Pedro Franco" cazaba con
//    "Franco Armani").
//  - Un mismo tmId no puede quedar asignado a dos starPlayers: es una persona
//    real y no puede ser dos jugadores a la vez.
//  - Los ids de club se resuelven con el buscador de Transfermarkt y luego se
//    VERIFICAN contra el nombre que declara la propia pagina del club. El
//    buscador devuelve resultados difusos (buscar "Bogota FC" devolvia
//    Millonarios primero; "Real Cundinamarca", Valledupar) y hay homonimos de
//    otros paises (existen un Leones FC y un Tigres FC no colombianos).
//  - currentClubName aparece solo si Transfermarkt dice que el jugador hoy
//    juega en otro club (58 de 557): los planteles de data.ts son de una
//    temporada anterior. Es informativo y NADIE lo consume todavia -- no mueve
//    a nadie de equipo.

export interface TmSquadData {
  age: number;
  tmId: string;
  tmName: string;
  tmPosition?: string;
  currentClubName?: string;
}

export const TM_SQUAD_ENRICHMENT: Record<string, TmSquadData> = {
  'acassuso|David Escalante (ST)': { age: 35, tmId: '223759', tmName: 'David Escalante', tmPosition: 'Delantero centro' },
  'acassuso|Joel Gonzalo Ghirardello (CB)': { age: 30, tmId: '972373', tmName: 'Joel Ghirardello', tmPosition: 'Defensa central' },
  'acassuso|Juan Ponce de León (RB)': { age: 26, tmId: '1087673', tmName: 'Juan Ponce de León', tmPosition: 'Lateral derecho' },
  'acassuso|Kevin Dubini (CAM)': { age: 33, tmId: '629850', tmName: 'Kevin Dubini', tmPosition: 'Mediocentro ofensivo' },
  'acassuso|Lucas Pioli (CB)': { age: 25, tmId: '1461075', tmName: 'Lucas Pioli', tmPosition: 'Defensa central' },
  'acassuso|Lucas Rey (RW)': { age: 27, tmId: '1383895', tmName: 'Lucas Rey', tmPosition: 'Extremo derecho' },
  'acassuso|Mariano Monllor (GK)': { age: 37, tmId: '697403', tmName: 'Mariano Monllor', tmPosition: 'Portero' },
  'acassuso|Nahuel Petillo (CM)': { age: 24, tmId: '1187402', tmName: 'Nahuel Petillo', tmPosition: 'Pivote' },
  'acassuso|Ramiro Reynoso (CM)': { age: 27, tmId: '1107414', tmName: 'Ramiro Reynoso', tmPosition: 'Mediocentro' },
  'acassuso|Álex Ruiz (LB)': { age: 26, tmId: '1203923', tmName: 'Álex Ruiz', tmPosition: 'Lateral izquierdo' },
  'agropecuario|Alan Aguirre (CB)': { age: 32, tmId: '282607', tmName: 'Alan Aguirre', tmPosition: 'Defensa central' },
  'agropecuario|Alejandro Gagliardi (ST)': { age: 36, tmId: '88071', tmName: 'Alejandro Gagliardi', tmPosition: 'Delantero centro' },
  'agropecuario|Brian Blando (ST)': { age: 31, tmId: '530444', tmName: 'Brian Blando', tmPosition: 'Delantero centro' },
  'agropecuario|Carlos Auzqui (CAM)': { age: 35, tmId: '100001', tmName: 'Carlos Auzqui', tmPosition: 'Extremo derecho' },
  'agropecuario|Luciano Acosta (GK)': { age: 22, tmId: '1305327', tmName: 'Luciano Acosta', tmPosition: 'Portero' },
  'agropecuario|Milton Ramos (LB)': { age: 31, tmId: '433771', tmName: 'Milton Ramos', tmPosition: 'Mediocentro' },
  'agropecuario|Rodrigo Castro (CAM)': { age: 33, tmId: '238661', tmName: 'Rodrigo Castro', tmPosition: 'Mediocentro ofensivo' },
  'agropecuario|Rodrigo Mosqueira (LM)': { age: 30, tmId: '1031533', tmName: 'Rodrigo Mosqueira', tmPosition: 'Extremo izquierdo' },
  'agropecuario|Tomás Lecanda (CB)': { age: 24, tmId: '661134', tmName: 'Tomás Lecanda', tmPosition: 'Defensa central' },
  'aguilas|Andrés Ricaurte (CM)': { age: 34, tmId: '253846', tmName: 'Andrés Ricaurte', tmPosition: 'Mediocentro' },
  'aguilas|Dylan Lozano (RB)': { age: 24, tmId: '950839', tmName: 'Dylan Lozano', tmPosition: 'Lateral derecho' },
  'aguilas|Frank Lozano (CDM)': { age: 32, tmId: '262931', tmName: 'Frank Lozano', tmPosition: 'Pivote' },
  'aguilas|Iván Rojas (CDM)': { age: 29, tmId: '474677', tmName: 'Iván Rojas', tmPosition: 'Pivote' },
  'aguilas|John García (CB)': { age: 37, tmId: '356360', tmName: 'John García', tmPosition: 'Defensa central' },
  'aguilas|Sebastián Rodríguez (CB)': { age: 25, tmId: '649878', tmName: 'Sebastián Rodríguez', tmPosition: 'Defensa central' },
  'aldosivi|Alan Sosa (LM)': { age: 23, tmId: '1103941', tmName: 'Alan Sosa', tmPosition: 'Extremo izquierdo' },
  'aldosivi|Axel Werner (GK)': { age: 30, tmId: '236734', tmName: 'Axel Werner', tmPosition: 'Portero', currentClubName: 'Rosario Central' },
  'aldosivi|Esteban Rolón (CDM)': { age: 31, tmId: '399887', tmName: 'Esteban Rolón', tmPosition: 'Pivote' },
  'aldosivi|Guillermo Enrique (RB)': { age: 26, tmId: '953990', tmName: 'Guillermo Enrique', tmPosition: 'Lateral derecho' },
  'aldosivi|Ignacio Chicco (GK)': { age: 30, tmId: '503329', tmName: 'Ignacio Chicco', tmPosition: 'Portero' },
  'aldosivi|Joaquín Novillo (CB)': { age: 28, tmId: '426523', tmName: 'Joaquín Novillo', tmPosition: 'Defensa central', currentClubName: 'Quilmes' },
  'aldosivi|Lucas Rodríguez (LB)': { age: 32, tmId: '171593', tmName: 'Lucas Rodríguez', tmPosition: 'Lateral izquierdo' },
  'aldosivi|Nicolás Cordero (ST)': { age: 27, tmId: '652948', tmName: 'Nicolás Cordero', tmPosition: 'Delantero centro' },
  'aldosivi|Nicolás Zalazar (CB)': { age: 29, tmId: '471640', tmName: 'Nicolás Zalazar', tmPosition: 'Defensa central' },
  'aldosivi|Néstor Breitenbruch (CB)': { age: 30, tmId: '334056', tmName: 'Néstor Breitenbruch', tmPosition: 'Defensa central' },
  'aldosivi|Sebastián Moyano (GK)': { age: 35, tmId: '148789', tmName: 'Sebastián Moyano', tmPosition: 'Portero' },
  'alianza_fc|Déinner Quiñones (RM)': { age: 30, tmId: '352566', tmName: 'Déinner Quiñones', tmPosition: 'Extremo derecho' },
  'alianza_fc|Jhildrey Lasso': { age: 24, tmId: '911120', tmName: 'Jhildrey Lasso', tmPosition: 'Lateral izquierdo' },
  'alianza_fc|Misael Martínez (ST)': { age: 28, tmId: '657009', tmName: 'Misael Martínez', tmPosition: 'Delantero centro' },
  'alianza_fc|Pedro Franco': { age: 35, tmId: '118998', tmName: 'Pedro Franco', tmPosition: 'Defensa central' },
  'all_boys|Agustin Gallo (CM)': { age: 27, tmId: '952149', tmName: 'Agustín Gallo', tmPosition: 'Delantero centro', currentClubName: 'Tristán Suárez' },
  'all_boys|Alejo Tabares (LM)': { age: 25, tmId: '756988', tmName: 'Alejo Tabares', tmPosition: 'Lateral izquierdo' },
  'all_boys|Emiliano Purita (RB)': { age: 29, tmId: '471638', tmName: 'Emiliano Purita', tmPosition: 'Lateral derecho' },
  'all_boys|Franco Quiróz (LB)': { age: 28, tmId: '534032', tmName: 'Franco Quiroz', tmPosition: 'Lateral izquierdo' },
  'all_boys|Hernán Grana (RB)': { age: 41, tmId: '78482', tmName: 'Hernán Grana', tmPosition: 'Lateral derecho' },
  'all_boys|Iván Zafarana (CB)': { age: 31, tmId: '849618', tmName: 'Iván Zafarana', tmPosition: 'Defensa central' },
  'all_boys|Juan Pablo Noce (GK)': { age: 28, tmId: '503346', tmName: 'Juan Pablo Noce', tmPosition: 'Portero' },
  'all_boys|Matías Nouet (RW)': { age: 33, tmId: '539165', tmName: 'Matías Nouet', tmPosition: 'Extremo derecho' },
  'all_boys|Maximiliano Coronel (CB)': { age: 37, tmId: '125082', tmName: 'Maximiliano Coronel', tmPosition: 'Defensa central' },
  'almagro|Andrés Chávez (ST)': { age: 35, tmId: '193768', tmName: 'Andrés Chávez', tmPosition: 'Delantero centro', currentClubName: 'Aldosivi' },
  'almagro|Enzo Martínez (LM)': { age: 28, tmId: '578737', tmName: 'Enzo Martínez', tmPosition: 'Defensa central', currentClubName: 'Gimnasia y Esgrima La Plata' },
  'almirante_brown|Agustín Dattola (CB)': { age: 27, tmId: '865490', tmName: 'Agustín Dattola', tmPosition: 'Defensa central' },
  'almirante_brown|Facundo Quignon (CDM)': { age: 33, tmId: '131218', tmName: 'Facundo Quignón', tmPosition: 'Pivote' },
  'almirante_brown|Gustavo Cabral (CB)': { age: 40, tmId: '30677', tmName: 'Gustavo Cabral', tmPosition: 'Defensa central' },
  'almirante_brown|Jonatan Goya (CAM)': { age: 37, tmId: '528399', tmName: 'Jonatan Goya', tmPosition: 'Mediocentro' },
  'almirante_brown|Leonardo Jara (RB)': { age: 35, tmId: '116163', tmName: 'Leonardo Jara', tmPosition: 'Lateral derecho' },
  'almirante_brown|Máximo Levi (CB)': { age: 30, tmId: '560727', tmName: 'Máximo Levi', tmPosition: 'Defensa central' },
  'almirante_brown|Nazareno Bazán (ST)': { age: 27, tmId: '555846', tmName: 'Nazareno Bazán', tmPosition: 'Delantero centro' },
  'almirante_brown|Ramiro Fernández (LB)': { age: 30, tmId: '690436', tmName: 'Ramiro Fernández', tmPosition: 'Lateral izquierdo' },
  'almirante_brown|Tobías Zárate (ST)': { age: 26, tmId: '742603', tmName: 'Tobías Zárate', tmPosition: 'Mediocentro ofensivo' },
  'almirante_brown|Tomas Villoldo (LB)': { age: 31, tmId: '423179', tmName: 'Tomás Villoldo', tmPosition: 'Lateral izquierdo' },
  'alvarado|Tomás Fernández (CB)': { age: 22, tmId: '1153735', tmName: 'Tomás Fernández', tmPosition: 'Defensa central', currentClubName: 'Tigre' },
  'america_cali|Adrián Ramos (ST)': { age: 40, tmId: '73782', tmName: 'Adrián Ramos', tmPosition: 'Delantero centro' },
  'america_cali|Brayan Córdoba (CB)': { age: 26, tmId: '585356', tmName: 'Brayan Córdoba', tmPosition: 'Defensa central' },
  'america_cali|Dany Rosero (CB)': { age: 32, tmId: '283399', tmName: 'Dany Rosero', tmPosition: 'Defensa central' },
  'america_cali|Jean (GK)': { age: 30, tmId: '371231', tmName: 'Jean', tmPosition: 'Portero' },
  'america_cali|Jhon Murillo (RW)': { age: 30, tmId: '308560', tmName: 'Jhon Murillo', tmPosition: 'Extremo derecho' },
  'america_cali|Luis Quiñones (ST)': { age: 35, tmId: '227404', tmName: 'Luis Quiñónes', tmPosition: 'Extremo derecho' },
  'america_cali|Marlon Torres (CB)': { age: 30, tmId: '485731', tmName: 'Marlon Torres', tmPosition: 'Defensa central' },
  'america_cali|Rafael Carrascal (CM)': { age: 33, tmId: '260385', tmName: 'Rafael Carrascal', tmPosition: 'Mediocentro' },
  'america_cali|Yani Quintero (CM)': { age: 24, tmId: '655335', tmName: 'Yani Quintero', tmPosition: 'Pivote' },
  'america_cali|Yeison Guzmán (CAM)': { age: 28, tmId: '498687', tmName: 'Yeison Guzmán', tmPosition: 'Mediocentro ofensivo' },
  'argentinos_jrs|Alan Lescano': { age: 24, tmId: '991134', tmName: 'Alan Lescano', tmPosition: 'Mediocentro ofensivo' },
  'argentinos_jrs|Diego Rodríguez': { age: 37, tmId: '90800', tmName: 'Diego Rodríguez', tmPosition: 'Portero' },
  'atl_tucuman|Gastón Suso (CB)': { age: 35, tmId: '469776', tmName: 'Gastón Suso', tmPosition: 'Defensa central' },
  'atl_tucuman|Gianluca Ferrari (CB)': { age: 29, tmId: '340507', tmName: 'Gianluca Ferrari', tmPosition: 'Defensa central' },
  'atl_tucuman|Kevin Ortiz (CM)': { age: 25, tmId: '984079', tmName: 'Kevin Ortiz', tmPosition: 'Pivote' },
  'atl_tucuman|Leandro Díaz (ST)': { age: 34, tmId: '140214', tmName: 'Leandro Díaz', tmPosition: 'Delantero centro' },
  'atl_tucuman|Leonel Di Plácido (RB)': { age: 32, tmId: '322843', tmName: 'Leonel Di Plácido', tmPosition: 'Lateral derecho' },
  'atl_tucuman|Luis Ingolotti (GK)': { age: 26, tmId: '552636', tmName: 'Luis Ingolotti', tmPosition: 'Portero' },
  'atl_tucuman|Martín Benítez (CAM)': { age: 32, tmId: '189418', tmName: 'Martín Benítez', tmPosition: 'Mediocentro ofensivo' },
  'atl_tucuman|Maximiliano Villa (RB)': { age: 29, tmId: '521234', tmName: 'Maximiliano Villa', tmPosition: 'Lateral derecho' },
  'atl_tucuman|Ramiro Ruiz Rodríguez (RM)': { age: 26, tmId: '633048', tmName: 'Ramiro Ruiz Rodríguez', tmPosition: 'Delantero centro' },
  'atl_tucuman|Renzo Tesuri (RM)': { age: 30, tmId: '457666', tmName: 'Renzo Tesuri', tmPosition: 'Interior derecho' },
  'atlanta|Alejandro Quintana (ST)': { age: 34, tmId: '135732', tmName: 'Alejandro Quintana', tmPosition: 'Delantero centro' },
  'atlanta|Braian Rivero (CDM)': { age: 30, tmId: '400896', tmName: 'Braian Rivero', tmPosition: 'Mediocentro' },
  'atlanta|Christian Bernardi (CAM)': { age: 36, tmId: '267572', tmName: 'Christian Bernardi', tmPosition: 'Extremo derecho' },
  'atlanta|Federico Castro (ST)': { age: 32, tmId: '359042', tmName: 'Federico Castro', tmPosition: 'Delantero centro' },
  'atlanta|Francisco Rago (GK)': { age: 37, tmId: '671896', tmName: 'Francisco Rago', tmPosition: 'Portero' },
  'atlanta|Gustavo Mendoza (CDM)': { age: 31, tmId: '997368', tmName: 'Gustavo Mendoza', tmPosition: 'Pivote' },
  'atlanta|Leonel Galeano (CB)': { age: 34, tmId: '124244', tmName: 'Leonel Galeano', tmPosition: 'Defensa central' },
  'atlanta|Martin García (RB)': { age: 20, tmId: '1282681', tmName: 'Martín García', tmPosition: 'Mediocentro', currentClubName: 'Aldosivi' },
  'atlanta|Nicolás Previtali (CDM)': { age: 31, tmId: '690437', tmName: 'Nicolás Previtali', tmPosition: 'Pivote' },
  'atlanta|Rodrigo Moreira (CB)': { age: 30, tmId: '294878', tmName: 'Rodrigo Moreira', tmPosition: 'Defensa central' },
  'atlanta|Tomás Castro Ponce (CAM)': { age: 25, tmId: '836491', tmName: 'Tomás Castro Ponce', tmPosition: 'Interior derecho' },
  'banfield|Bruno Sepúlveda (ST)': { age: 33, tmId: '690718', tmName: 'Bruno Sepúlveda', tmPosition: 'Delantero centro' },
  'banfield|Danilo Arboleda (CB)': { age: 31, tmId: '364586', tmName: 'Danilo Arboleda', tmPosition: 'Defensa central' },
  'banfield|Facundo Sanguinetti (GK)': { age: 25, tmId: '870032', tmName: 'Facundo Sanguinetti', tmPosition: 'Portero' },
  'banfield|Gino Santilli (GK)': { age: 24, tmId: '881009', tmName: 'Gino Santilli', tmPosition: 'Portero' },
  'banfield|Ignacio Abraham (LB)': { age: 28, tmId: '985269', tmName: 'Ignacio Abraham', tmPosition: 'Lateral izquierdo' },
  'banfield|Lautaro Ríos (CM)': { age: 25, tmId: '878220', tmName: 'Lautaro Ríos', tmPosition: 'Pivote' },
  'banfield|Mauro Méndez (ST)': { age: 27, tmId: '675468', tmName: 'Mauro Méndez', tmPosition: 'Delantero centro', currentClubName: 'Estudiantes de La Plata' },
  'banfield|Nicolas Meriano (CB)': { age: 25, tmId: '941511', tmName: 'Nicolás Meriano', tmPosition: 'Defensa central' },
  'banfield|Nicolás Colazo (LB)': { age: 36, tmId: '116277', tmName: 'Nicolás Colazo', tmPosition: 'Lateral izquierdo', currentClubName: 'Quilmes' },
  'banfield|Santiago López García (RB)': { age: 28, tmId: '654813', tmName: 'Santiago López García', tmPosition: 'Interior derecho' },
  'banfield|Sergio Vittor (CB)': { age: 37, tmId: '91597', tmName: 'Sergio Vittor', tmPosition: 'Defensa central', currentClubName: 'Chacarita' },
  'barracas|Damián Martínez (RB)': { age: 36, tmId: '107282', tmName: 'Damián Martínez', tmPosition: 'Lateral derecho' },
  'barracas|Dardo Miloc (CDM)': { age: 35, tmId: '118375', tmName: 'Dardo Miloc', tmPosition: 'Pivote' },
  'barracas|Facundo Bruera (ST)': { age: 27, tmId: '538880', tmName: 'Facundo Bruera', tmPosition: 'Delantero centro', currentClubName: 'San Lorenzo de Almagro' },
  'barracas|Gastón Campi (CB)': { age: 35, tmId: '292174', tmName: 'Gastón Campi', tmPosition: 'Defensa central' },
  'barracas|Gonzalo Maroni (CAM)': { age: 27, tmId: '441385', tmName: 'Gonzalo Maroni', tmPosition: 'Mediocentro ofensivo' },
  'barracas|Gonzalo Morales (ST)': { age: 23, tmId: '1064936', tmName: 'Gonzalo Morales', tmPosition: 'Delantero centro' },
  'barracas|Iván Tapia (CAM)': { age: 27, tmId: '697405', tmName: 'Iván Tapia', tmPosition: 'Mediocentro ofensivo' },
  'barracas|Juan Espínola (GK)': { age: 31, tmId: '532557', tmName: 'Juan Espínola', tmPosition: 'Portero' },
  'barracas|Rodrigo Bogarín (CAM)': { age: 29, tmId: '418859', tmName: 'Rodrigo Bogarín', tmPosition: 'Mediocentro ofensivo' },
  'barracas|Rodrigo Insua (LB)': { age: 28, tmId: '721235', tmName: 'Rodrigo Insúa', tmPosition: 'Lateral izquierdo' },
  'barracas|Yonatthan Rak (CB)': { age: 32, tmId: '227781', tmName: 'Yonatthan Rak', tmPosition: 'Defensa central' },
  'barranquilla_fc|Cristian Peñate (ST)': { age: 21, tmId: '1110702', tmName: 'Cristian Peñate' },
  'barranquilla_fc|Jhon Cortez (LB)': { age: 20, tmId: '1289824', tmName: 'Jhon Cortez', tmPosition: 'Lateral izquierdo' },
  'barranquilla_fc|José Caicedo (CB)': { age: 25, tmId: '908349', tmName: 'José Caicedo', tmPosition: 'Defensa central' },
  'barranquilla_fc|Juan Lemus (GK)': { age: 27, tmId: '588983', tmName: 'Juan Lemus', tmPosition: 'Portero' },
  'barranquilla_fc|Miguel Agamez (CM)': { age: 17, tmId: '1285379', tmName: 'Miguel Agámez', tmPosition: 'Mediocentro' },
  'barranquilla_fc|Miller Bacca (ST)': { age: 22, tmId: '1124476', tmName: 'Miller Bacca', tmPosition: 'Delantero centro' },
  'barranquilla_fc|Sebastián Guerra (GK)': { age: 25, tmId: '567016', tmName: 'Sebastián Guerra', tmPosition: 'Portero' },
  'barranquilla_fc|Yeferson Moreno (RB)': { age: 22, tmId: '1040937', tmName: 'Yeferson Moreno', tmPosition: 'Lateral derecho' },
  'belgrano|Lucas Passerini': { age: 32, tmId: '334586', tmName: 'Lucas Passerini', tmPosition: 'Delantero centro' },
  'belgrano|Ulises Sánchez': { age: 28, tmId: '724220', tmName: 'Ulises Sánchez', tmPosition: 'Extremo derecho', currentClubName: 'Gimnasia de Mendoza' },
  'boca|Ayrton Costa (CB)': { age: 27, tmId: '842910', tmName: 'Ayrton Costa', tmPosition: 'Defensa central' },
  'boca|Carlos Palacios (CAM)': { age: 26, tmId: '571219', tmName: 'Carlos Palacios', tmPosition: 'Mediocentro ofensivo' },
  'boca|Exequiel Zeballos (LW)': { age: 24, tmId: '661132', tmName: 'Exequiel Zeballos', tmPosition: 'Extremo derecho' },
  'boca|Lautaro Blanco (LB)': { age: 27, tmId: '831161', tmName: 'Lautaro Blanco', tmPosition: 'Lateral izquierdo' },
  'boca|Leandro Lozano (RB)': { age: 27, tmId: '665101', tmName: 'Leandro Lozano', tmPosition: 'Lateral derecho' },
  'boca|Leandro Paredes (CM)': { age: 32, tmId: '166237', tmName: 'Leandro Paredes', tmPosition: 'Pivote' },
  'boca|Miguel Ángel Merentiel (ST)': { age: 30, tmId: '481367', tmName: 'Miguel Merentiel', tmPosition: 'Delantero centro' },
  'boca|Rodrigo Battaglia (CDM)': { age: 35, tmId: '89297', tmName: 'Rodrigo Battaglia', tmPosition: 'Pivote' },
  'boca|Santiago Ascacíbar (CDM)': { age: 29, tmId: '423436', tmName: 'Santiago Ascacíbar', tmPosition: 'Pivote' },
  'boca|Sebastián Villa (RW)': { age: 30, tmId: '493000', tmName: 'Sebastián Villa', tmPosition: 'Extremo izquierdo' },
  'bogota_fc|Andrés Buelvas (ST)': { age: 25, tmId: '1460233', tmName: 'Andrés Buelvas' },
  'bogota_fc|Brayan Castro (RW)': { age: 24, tmId: '1116430', tmName: 'Brayan Castro', tmPosition: 'Extremo derecho' },
  'bogota_fc|Cristián Mosquera (RB)': { age: 25, tmId: '659709', tmName: 'Cristian Mosquera', tmPosition: 'Lateral derecho' },
  'bogota_fc|Harold Sandoval Lasso (ST)': { age: 24, tmId: '1101847', tmName: 'Harold Sandoval Lasso', tmPosition: 'Extremo derecho' },
  'bogota_fc|Juan Camilo Moreno (LB)': { age: 24, tmId: '671964', tmName: 'Juan Camilo Moreno', tmPosition: 'Lateral izquierdo' },
  'bogota_fc|Juan Martínez (LW)': { age: 24, tmId: '908381', tmName: 'Juan Martínez', tmPosition: 'Extremo izquierdo' },
  'bogota_fc|Kevin Castro (CDM)': { age: 27, tmId: '650828', tmName: 'Kevin Castro', tmPosition: 'Pivote' },
  'bogota_fc|Mauricio Medina (RB)': { age: 21, tmId: '1232888', tmName: 'Mauricio Medina', tmPosition: 'Lateral derecho' },
  'bogota_fc|Ronaldo Tavera (CDM)': { age: 31, tmId: '413554', tmName: 'Ronaldo Tavera', tmPosition: 'Pivote' },
  'bogota_fc|Santiago Ruiz (CB)': { age: 21, tmId: '1371707', tmName: 'Santiago Ruiz' },
  'boyaca_chico|Andrés Aedo (CDM)': { age: 22, tmId: '1074923', tmName: 'Andrés Aedo', tmPosition: 'Pivote' },
  'boyaca_chico|Arlen Banguero (CB)': { age: 26, tmId: '1118342', tmName: 'Arlen Banguero', tmPosition: 'Defensa central' },
  'boyaca_chico|Delio Ramírez (CM)': { age: 25, tmId: '751990', tmName: 'Delio Ramírez', tmPosition: 'Mediocentro' },
  'boyaca_chico|Jefferson Mena': { age: 37, tmId: '189390', tmName: 'Jefferson Mena', tmPosition: 'Defensa central' },
  'boyaca_chico|Juan Carlos Díaz (CDM)': { age: 25, tmId: '632290', tmName: 'Juan Díaz', tmPosition: 'Pivote' },
  'boyaca_chico|Rogerio Caicedo (GK)': { age: 32, tmId: '600616', tmName: 'Rogerio Caicedo', tmPosition: 'Portero' },
  'boyaca_chico|Sebastián Palma (CB)': { age: 27, tmId: '572041', tmName: 'Sebastián Palma', tmPosition: 'Defensa central' },
  'boyaca_chico|Sebastián Salazar (CM)': { age: 30, tmId: '355155', tmName: 'Sebastián Salazar', tmPosition: 'Mediocentro' },
  'boyaca_chico|Yaliston Martínez (LB)': { age: 26, tmId: '911027', tmName: 'Yaliston Martínez', tmPosition: 'Lateral izquierdo' },
  'boyaca_chico|Yesús Cabrera (CAM)': { age: 35, tmId: '133522', tmName: 'Yesús Cabrera', tmPosition: 'Mediocentro ofensivo' },
  'bucaramanga|Fabián Sambueza': { age: 37, tmId: '358015', tmName: 'Fabián Sambueza', tmPosition: 'Mediocentro ofensivo' },
  'bucaramanga|Omar Albornoz (LM)': { age: 30, tmId: '387605', tmName: 'Omar Albornoz', tmPosition: 'Extremo izquierdo' },
  'cali|Alejandro Rodríguez (GK)': { age: 25, tmId: '892082', tmName: 'Alejandro Rodríguez', tmPosition: 'Portero' },
  'cali|Avilés Hurtado (LW)': { age: 39, tmId: '148713', tmName: 'Avilés Hurtado', tmPosition: 'Extremo izquierdo' },
  'cali|Emanuel Reynoso (CAM)': { age: 30, tmId: '439626', tmName: 'Emanuel Reynoso', tmPosition: 'Mediocentro ofensivo' },
  'cali|Fabián Viáfara (RB)': { age: 34, tmId: '326011', tmName: 'Fabián Viáfara', tmPosition: 'Lateral derecho' },
  'cali|Felipe Aguilar (CB)': { age: 33, tmId: '260377', tmName: 'Felipe Aguilar', tmPosition: 'Defensa central', currentClubName: 'Central Córdoba' },
  'cali|Johan Martinez (LW)': { age: 24, tmId: '1053759', tmName: 'Johan Martínez', tmPosition: 'Extremo izquierdo' },
  'cali|Juan Dinenno (ST)': { age: 31, tmId: '288786', tmName: 'Juan Dinenno', tmPosition: 'Delantero centro' },
  'cali|Pedro Gallese (GK)': { age: 36, tmId: '95172', tmName: 'Pedro Gallese', tmPosition: 'Portero' },
  'cartagena|Aldo Montes (GK)': { age: 26, tmId: '906759', tmName: 'Aldo Montes', tmPosition: 'Portero' },
  'cartagena|Andrés Escobar (LW)': { age: 29, tmId: '653452', tmName: 'Andrés Escobar', tmPosition: 'Extremo izquierdo' },
  'cartagena|Cristian Graciano (RB)': { age: 23, tmId: '1118337', tmName: 'Cristian Graciano', tmPosition: 'Lateral derecho' },
  'cartagena|Didier Pino (CDM)': { age: 30, tmId: '460897', tmName: 'Didier Pino', tmPosition: 'Pivote' },
  'cartagena|Diego Castillo (ST)': { age: 26, tmId: '911913', tmName: 'Diego Castillo', tmPosition: 'Extremo izquierdo' },
  'cartagena|Fredy Montero (ST)': { age: 39, tmId: '73852', tmName: 'Fredy Montero', tmPosition: 'Delantero centro' },
  'cartagena|Jaen Carlos Pineda (CM)': { age: 28, tmId: '460693', tmName: 'Jaen Pineda', tmPosition: 'Mediocentro' },
  'cartagena|Jarlan Barrera (CAM)': { age: 30, tmId: '338219', tmName: 'Jarlan Barrera', tmPosition: 'Mediocentro ofensivo' },
  'cartagena|Juan Sebastian Herrera (RB)': { age: 25, tmId: '911963', tmName: 'Juan Herrera', tmPosition: 'Lateral derecho' },
  'cartagena|Luis Guevara (CM)': { age: 25, tmId: '1105567', tmName: 'Luis Guevara', tmPosition: 'Mediocentro' },
  'cartagena|Luis Yanes (LW)': { age: 19, tmId: '1157630', tmName: 'Luis Yanes', tmPosition: 'Extremo izquierdo' },
  'cartagena|Mauro Manotas (ST)': { age: 31, tmId: '325614', tmName: 'Mauro Manotas', tmPosition: 'Delantero centro' },
  'cartagena|Ronaldo Lora (CB)': { age: 29, tmId: '638277', tmName: 'Ronaldo Lora', tmPosition: 'Defensa central' },
  'central_cordoba|Alan Aguerre (GK)': { age: 35, tmId: '269784', tmName: 'Alan Aguerre', tmPosition: 'Portero' },
  'central_cordoba|Alejandro Maciel (CB)': { age: 29, tmId: '535033', tmName: 'Alejandro Maciel', tmPosition: 'Defensa central' },
  'central_cordoba|Ezequiel Naya (ST)': { age: 24, tmId: '909314', tmName: 'Ezequiel Naya', tmPosition: 'Delantero centro' },
  'central_cordoba|Facundo Mansilla (CB)': { age: 27, tmId: '833783', tmName: 'Facundo Mansilla', tmPosition: 'Defensa central' },
  'central_cordoba|Horacio Tijanovich (LM)': { age: 30, tmId: '380974', tmName: 'Horacio Tijanovich', tmPosition: 'Extremo izquierdo' },
  'central_cordoba|Juan Pablo Pignani (CB)': { age: 25, tmId: '984882', tmName: 'Juan Pablo Pignani', tmPosition: 'Defensa central' },
  'central_cordoba|Lucas González (CM)': { age: 26, tmId: '688778', tmName: 'Lucas González', tmPosition: 'Mediocentro' },
  'central_cordoba|Marco Iacobellis (RM)': { age: 26, tmId: '699886', tmName: 'Marco Iacobellis', tmPosition: 'Mediocentro ofensivo' },
  'central_cordoba|Matías Vera (CDM)': { age: 30, tmId: '368801', tmName: 'Matías Vera', tmPosition: 'Pivote' },
  'central_cordoba|Michael Santos (ST)': { age: 33, tmId: '178107', tmName: 'Michael Santos', tmPosition: 'Delantero centro' },
  'central_cordoba|Santiago Moyano (RB)': { age: 28, tmId: '568551', tmName: 'Santiago Moyano', tmPosition: 'Lateral derecho' },
  'central_norte|Agustin Aleo (LB)': { age: 28, tmId: '572088', tmName: 'Agustín Aleo', tmPosition: 'Lateral izquierdo' },
  'central_norte|Arián Pucheta (CB)': { age: 31, tmId: '496405', tmName: 'Arián Pucheta', tmPosition: 'Defensa central' },
  'central_norte|Franco Vedoya (RW)': { age: 25, tmId: '849620', tmName: 'Franco Vedoya', tmPosition: 'Extremo derecho' },
  'central_norte|Gonzalo Álvez (RM)': { age: 22, tmId: '668510', tmName: 'Gonzalo Álvez', tmPosition: 'Mediocentro ofensivo' },
  'central_norte|Joaquin Mateo (ST)': { age: 28, tmId: '544164', tmName: 'Joaquin Mateo', tmPosition: 'Mediapunta' },
  'central_norte|Leonardo Felissia (CB)': { age: 25, tmId: '990189', tmName: 'Leonardo Felissia', tmPosition: 'Defensa central' },
  'central_norte|Matías Villarreal (CDM)': { age: 34, tmId: '441076', tmName: 'Matías Villarreal', tmPosition: 'Pivote' },
  'central_norte|Mauricio Rosales (RB)': { age: 34, tmId: '251619', tmName: 'Mauricio Rosales', tmPosition: 'Lateral derecho' },
  'central_norte|Ramiro Costa (ST)': { age: 33, tmId: '186296', tmName: 'Ramiro Costa', tmPosition: 'Delantero centro' },
  'chaco_for_ever|Agustin Alonso (RM)': { age: 25, tmId: '1015522', tmName: 'Agustín Alonso', tmPosition: 'Extremo izquierdo', currentClubName: 'Gimnasia de Jujuy' },
  'chaco_for_ever|Andrés Lioi (RM)': { age: 29, tmId: '563336', tmName: 'Andrés Lioi', tmPosition: 'Interior derecho' },
  'chaco_for_ever|Bahiano García (CDM)': { age: 25, tmId: '1087676', tmName: 'Bahiano Garcia', tmPosition: 'Mediocentro' },
  'chaco_for_ever|Brian Nievas (CDM)': { age: 28, tmId: '661074', tmName: 'Brian Nievas', tmPosition: 'Pivote' },
  'chaco_for_ever|David Valdez (CB)': { age: 33, tmId: '267436', tmName: 'David Valdez', tmPosition: 'Defensa central' },
  'chaco_for_ever|Gabriel Ramírez (CM)': { age: 31, tmId: '459243', tmName: 'Gabriel Ramírez', tmPosition: 'Pivote', currentClubName: 'All Boys' },
  'chaco_for_ever|Gaston Canuto (GK)': { age: 38, tmId: '853458', tmName: 'Gastón Canuto', tmPosition: 'Portero' },
  'chaco_for_ever|Lucas Pruzzo (LB)': { age: 32, tmId: '503067', tmName: 'Lucas Pruzzo', tmPosition: 'Lateral izquierdo' },
  'chaco_for_ever|Ricardo Garay (CB)': { age: 29, tmId: '480419', tmName: 'Ricardo Garay', tmPosition: 'Defensa central' },
  'chaco_for_ever|Tomás Bolzicco (ST)': { age: 31, tmId: '369707', tmName: 'Tomás Bolzicco', tmPosition: 'Delantero centro' },
  'cipoletti|Marcos Pérez (CM)': { age: 35, tmId: '76648', tmName: 'Marco Pérez', tmPosition: 'Delantero centro', currentClubName: 'Deportivo Pereira' },
  'colegiales|Elías Ocampo (RM)': { age: 22, tmId: '1225845', tmName: 'Elías Ocampo', tmPosition: 'Interior derecho' },
  'colegiales|Emanuel Insua (LB)': { age: 35, tmId: '226006', tmName: 'Emanuel Insúa', tmPosition: 'Lateral izquierdo' },
  'colegiales|Facundo Rivero (CB)': { age: 32, tmId: '997377', tmName: 'Facundo Rivero', tmPosition: 'Defensa central' },
  'colegiales|Leandro Martínez Montagnoli (CB)': { age: 39, tmId: '249731', tmName: 'Leandro Martínez Montagnoli', tmPosition: 'Defensa central' },
  'colegiales|Leonardo González (RW)': { age: 25, tmId: '884004', tmName: 'Leonardo González', tmPosition: 'Extremo derecho' },
  'colegiales|Lucio Castillo (CAM)': { age: 24, tmId: '880661', tmName: 'Lucio Castillo', tmPosition: 'Mediapunta' },
  'colegiales|Mateo Mamaní (ST)': { age: 24, tmId: '830110', tmName: 'Mateo Mamani', tmPosition: 'Delantero centro' },
  'colegiales|Mauro Albertengo (ST)': { age: 36, tmId: '431183', tmName: 'Mauro Albertengo', tmPosition: 'Delantero centro' },
  'colegiales|Nicolás Toloza (ST)': { age: 27, tmId: '925438', tmName: 'Nicolás Toloza', tmPosition: 'Delantero centro' },
  'colon|Facundo Castro (ST)': { age: 30, tmId: '332252', tmName: 'Facundo Castro', tmPosition: 'Delantero centro', currentClubName: 'Nueva Chicago' },
  'colon|Lucas Cano (ST)': { age: 31, tmId: '216036', tmName: 'Lucas Cano', tmPosition: 'Delantero centro', currentClubName: 'All Boys' },
  'colon|Matías Godoy (LM)': { age: 24, tmId: '582168', tmName: 'Matías Godoy', tmPosition: 'Extremo izquierdo', currentClubName: 'Aldosivi' },
  'cucuta|Jhon Quiñones (CB)': { age: 22, tmId: '1139706', tmName: 'Jhon Alexander Quiñones', tmPosition: 'Defensa central' },
  'cucuta|Joao Abonia (RW)': { age: 26, tmId: '907797', tmName: 'Joao Abonia', tmPosition: 'Lateral derecho' },
  'cucuta|Juan Diego Ceballos (CM)': { age: 27, tmId: '653400', tmName: 'Juan Ceballos', tmPosition: 'Mediocentro' },
  'cucuta|Marlon Carabali (RW)': { age: 23, tmId: '942666', tmName: 'Marlon Carabalí', tmPosition: 'Extremo derecho' },
  'cucuta|Mauricio Duarte (LB)': { age: 34, tmId: '213469', tmName: 'Mauricio Duarte', tmPosition: 'Lateral izquierdo' },
  'cucuta|Víctor Mejía (CM)': { age: 33, tmId: '287534', tmName: 'Víctor Mejía', tmPosition: 'Pivote' },
  'cundinamarca_fc|Iván Camacho (CDM)': { age: 22, tmId: '1007731', tmName: 'Iván Camacho', tmPosition: 'Pivote' },
  'cundinamarca_fc|Jhon Córtes (LB)': { age: 22, tmId: '1408999', tmName: 'Jhon Cortés' },
  'cundinamarca_fc|Jhon Suaza (CB)': { age: 24, tmId: '1047549', tmName: 'Jhon Suaza', tmPosition: 'Defensa central' },
  'cundinamarca_fc|Jose Cundumi (ST)': { age: 21, tmId: '1232886', tmName: 'Jose Cundumi' },
  'cundinamarca_fc|Juan David Hoyos (CDM)': { age: 21, tmId: '911081', tmName: 'Juan David Hoyos', tmPosition: 'Pivote' },
  'cundinamarca_fc|Juan Salcedo (ST)': { age: 33, tmId: '460694', tmName: 'Juan Salcedo', tmPosition: 'Delantero centro' },
  'cundinamarca_fc|Leider Montaño (ST)': { age: 22, tmId: '1246629', tmName: 'Leider Montaño', tmPosition: 'Delantero centro' },
  'cundinamarca_fc|Onel Acosta (LB)': { age: 26, tmId: '907564', tmName: 'Onel Acosta', tmPosition: 'Lateral izquierdo' },
  'cundinamarca_fc|William Dávila (CAM)': { age: 25, tmId: '1038870', tmName: 'William Dávila', tmPosition: 'Mediocentro ofensivo' },
  'cundinamarca_fc|Yan Vega (ST)': { age: 21, tmId: '1385743', tmName: 'Yan Vega' },
  'defensa_y_justicia|Cristopher Fiermarín': { age: 28, tmId: '563089', tmName: 'Cristopher Fiermarín', tmPosition: 'Portero', currentClubName: 'Atlético Bucaramanga' },
  'defensa_y_justicia|Kevin Gutiérrez': { age: 29, tmId: '554799', tmName: 'Kevin Gutiérrez', tmPosition: 'Pivote', currentClubName: 'Argentinos Juniors' },
  'defensa_y_justicia|Nicolás Fernández': { age: 30, tmId: '333921', tmName: 'Nicolás Fernández', tmPosition: 'Delantero centro', currentClubName: 'Belgrano de Córdoba' },
  'dep_maipu|Fausto Emanuel Montero (CM)': { age: 37, tmId: '144237', tmName: 'Fausto Montero', tmPosition: 'Pivote' },
  'dep_maipu|Gastón Mansilla (RM)': { age: 29, tmId: '912725', tmName: 'Gastón Mansilla', tmPosition: 'Mediocentro' },
  'dep_maipu|Juan Pablo Gobetto (CM)': { age: 30, tmId: '543588', tmName: 'Juan Pablo Gobetto', tmPosition: 'Mediocentro' },
  'dep_maipu|Luciano Arnijas (CM)': { age: 23, tmId: '1034446', tmName: 'Luciano Arnijas', tmPosition: 'Defensa central' },
  'dep_maipu|Matias Viguet (LM)': { age: 28, tmId: '696972', tmName: 'Matías Viguet', tmPosition: 'Extremo izquierdo' },
  'dep_maipu|Mirko Bonfigli (CM)': { age: 22, tmId: '1147600', tmName: 'Mirko Bonfigli', tmPosition: 'Mediocentro' },
  'dep_maipu|Nahuel Galardi (GK)': { age: 24, tmId: '1251312', tmName: 'Nahuel Galardi', tmPosition: 'Portero' },
  'dep_moron|Braian Salvareschi (CB)': { age: 27, tmId: '697054', tmName: 'Braian Salvareschi', tmPosition: 'Defensa central' },
  'dep_moron|Francisco Flores (CB)': { age: 24, tmId: '661129', tmName: 'Francisco Flores', tmPosition: 'Defensa central' },
  'dep_moron|Franco Toloza (ST)': { age: 32, tmId: '726764', tmName: 'Franco Toloza', tmPosition: 'Delantero centro' },
  'dep_moron|Gonzalo Berterame (RM)': { age: 30, tmId: '697651', tmName: 'Gonzalo Berterame', tmPosition: 'Mediocentro ofensivo' },
  'dep_moron|Joaquín Livera (LB)': { age: 26, tmId: '996929', tmName: 'Joaquín Livera', tmPosition: 'Lateral izquierdo' },
  'dep_moron|Juan Cruz Esquivel (LW)': { age: 25, tmId: '654819', tmName: 'Juan Cruz Esquivel', tmPosition: 'Extremo izquierdo' },
  'dep_moron|Juan Manuel Olivares (CM)': { age: 38, tmId: '67824', tmName: 'Juan Manuel Olivares', tmPosition: 'Mediocentro ofensivo' },
  'dep_moron|Julio Salvá (GK)': { age: 39, tmId: '67828', tmName: 'Julio Salvá', tmPosition: 'Portero' },
  'dep_moron|Mariano Bíttolo (LB)': { age: 36, tmId: '105842', tmName: 'Mariano Bíttolo', tmPosition: 'Lateral izquierdo' },
  'dep_moron|Matías Benítez (RW)': { age: 25, tmId: '879586', tmName: 'Matías Benítez', tmPosition: 'Delantero centro' },
  'dep_moron|Santiago Kubiszyn (CAM)': { age: 23, tmId: '891696', tmName: 'Santiago Kubiszyn', tmPosition: 'Mediocentro ofensivo' },
  'dock_sud|Gonzalo Gómez (RM)': { age: 40, tmId: '710589', tmName: 'Gonzalo Gómez', tmPosition: 'Portero', currentClubName: 'Gimnasia de Jujuy' },
  'dock_sud|Santiago Villarreal (RB)': { age: 20, tmId: '1305339', tmName: 'Santiago Villarreal', tmPosition: 'Mediocentro ofensivo', currentClubName: 'Gimnasia y Esgrima La Plata' },
  'envigado_fc|Jaime Mora (GK)': { age: 29, tmId: '480680', tmName: 'Jaime Mora', tmPosition: 'Portero' },
  'envigado_fc|Luis Díaz (Jr)': { age: 22, tmId: '926365', tmName: 'Luis Díaz', tmPosition: 'Extremo derecho' },
  'estudiantes_lp|Adolfo Gaich': { age: 27, tmId: '608469', tmName: 'Adolfo Gaich', tmPosition: 'Delantero centro' },
  'estudiantes_lp|Enzo Pérez': { age: 40, tmId: '56066', tmName: 'Enzo Pérez', tmPosition: 'Pivote', currentClubName: 'Deportivo Maipú' },
  'estudiantes_lp|Guido Carrillo': { age: 35, tmId: '184672', tmName: 'Guido Carrillo', tmPosition: 'Delantero centro' },
  'estudiantes_lp|Tomás Palacios': { age: 23, tmId: '993645', tmName: 'Tomás Palacios', tmPosition: 'Defensa central' },
  'estudiantes_rc|Gastón Arturia': { age: 26, tmId: '971529', tmName: 'Gastón Arturia', tmPosition: 'Defensa central', currentClubName: 'Sarmiento' },
  'estudiantes_rc|Tomás González': { age: 23, tmId: '989579', tmName: 'Tomás González', tmPosition: 'Delantero centro', currentClubName: 'Riestra' },
  'estudiantes_rc|Williams Barlasina': { age: 28, tmId: '836282', tmName: 'Williams Barlasina', tmPosition: 'Portero', currentClubName: 'Fortaleza FC' },
  'fortaleza_fc|Sebastián Navarro': { age: 26, tmId: '745937', tmName: 'Sebastián Navarro', tmPosition: 'Mediocentro' },
  'gimnasia_lp|Leonardo Morales': { age: 35, tmId: '457061', tmName: 'Leonardo Morales', tmPosition: 'Defensa central', currentClubName: 'Belgrano de Córdoba' },
  'gimnasia_lp|Nelson Insfrán': { age: 31, tmId: '660280', tmName: 'Nelson Insfrán', tmPosition: 'Portero' },
  'gimnasia_mza|Aaron Spetale': { age: 26, tmId: '965683', tmName: 'Aaron Spetale', tmPosition: 'Delantero centro', currentClubName: 'Quilmes' },
  'gimnasia_mza|Leandro Ciccolini': { age: 31, tmId: '653692', tmName: 'Leandro Ciccolini', tmPosition: 'Extremo derecho', currentClubName: 'Defensores de Belgrano' },
  'gimnasia_mza|Maximiliano Padilla': { age: 31, tmId: '189442', tmName: 'Maximiliano Padilla', tmPosition: 'Defensa central', currentClubName: 'Central Norte' },
  'godoy_cruz|Esteban Burgos (CB)': { age: 34, tmId: '337922', tmName: 'Esteban Burgos', tmPosition: 'Defensa central' },
  'godoy_cruz|Federico Milo (LB)': { age: 34, tmId: '283395', tmName: 'Federico Milo', tmPosition: 'Lateral izquierdo' },
  'godoy_cruz|Lucas Arce (RB)': { age: 28, tmId: '754470', tmName: 'Lucas Arce', tmPosition: 'Lateral derecho' },
  'godoy_cruz|Martín Pino (ST)': { age: 28, tmId: '556906', tmName: 'Martín Pino', tmPosition: 'Delantero centro' },
  'godoy_cruz|Mateo Mendoza (CB)': { age: 21, tmId: '1103933', tmName: 'Mateo Mendoza', tmPosition: 'Defensa central' },
  'godoy_cruz|Matías Ramírez (LM)': { age: 27, tmId: '548301', tmName: 'Matías Ramírez', tmPosition: 'Extremo izquierdo', currentClubName: 'Águilas Doradas' },
  'godoy_cruz|Misael Sosa (RW)': { age: 24, tmId: '996587', tmName: 'Misael Sosa', tmPosition: 'Mediapunta' },
  'godoy_cruz|Nahuel Ulariaga (ST)': { age: 24, tmId: '845336', tmName: 'Nahuel Ulariaga', tmPosition: 'Delantero centro' },
  'godoy_cruz|Roberto Ramírez (GK)': { age: 30, tmId: '332248', tmName: 'Roberto Ramírez', tmPosition: 'Portero' },
  'godoy_cruz|Vicente Poggi (CM)': { age: 24, tmId: '657744', tmName: 'Vicente Poggi', tmPosition: 'Mediocentro' },
  'huracan|Alejandro Martínez (LW)': { age: 29, tmId: '729356', tmName: 'Alejandro Martínez', tmPosition: 'Extremo izquierdo' },
  'huracan|Fabio Pereyra (CB)': { age: 36, tmId: '610248', tmName: 'Fabio Pereyra', tmPosition: 'Defensa central' },
  'huracan|Facundo Waller (LM)': { age: 29, tmId: '322696', tmName: 'Facundo Waller', tmPosition: 'Interior izquierdo' },
  'huracan|Federico Vera (RB)': { age: 28, tmId: '829967', tmName: 'Federico Vera', tmPosition: 'Lateral derecho' },
  'huracan|Hernán Galíndez (GK)': { age: 39, tmId: '77127', tmName: 'Hernán Galíndez', tmPosition: 'Portero' },
  'huracan|Leonardo Gil (CDM)': { age: 35, tmId: '125907', tmName: 'Leonardo Gil', tmPosition: 'Mediocentro' },
  'huracan|Lucas Blondel (RB)': { age: 29, tmId: '503348', tmName: 'Lucas Blondel', tmPosition: 'Lateral derecho' },
  'huracan|Nehuén Paz (CB)': { age: 33, tmId: '284724', tmName: 'Nehuén Paz', tmPosition: 'Defensa central' },
  'huracan|Sebastián Meza (GK)': { age: 26, tmId: '839030', tmName: 'Sebastián Meza', tmPosition: 'Portero' },
  'huracan|Óscar Romero (CAM)': { age: 34, tmId: '217886', tmName: 'Óscar Romero', tmPosition: 'Mediocentro ofensivo' },
  'indep_rivadavia|Gastón Gil Romero': { age: 33, tmId: '222052', tmName: 'Gastón Gil Romero', tmPosition: 'Pivote', currentClubName: 'Godoy Cruz' },
  'indep_rivadavia|Gonzalo Marinelli': { age: 37, tmId: '91815', tmName: 'Gonzalo Marinelli', tmPosition: 'Portero', currentClubName: 'Quilmes' },
  'indep_rivadavia|Matías Reali': { age: 28, tmId: '984692', tmName: 'Matías Reali', tmPosition: 'Extremo derecho', currentClubName: 'San Lorenzo de Almagro' },
  'indep_yumbo|Jhon Lerma (RB)': { age: 23, tmId: '983539', tmName: 'Jhon Lerma', tmPosition: 'Lateral derecho' },
  'independiente|Facundo Zabala (LB)': { age: 27, tmId: '660140', tmName: 'Facundo Zabala', tmPosition: 'Lateral izquierdo' },
  'independiente|Gabriel Ávalos (ST)': { age: 35, tmId: '358418', tmName: 'Gabriel Ávalos', tmPosition: 'Delantero centro' },
  'independiente|Iván Marcone (CDM)': { age: 36, tmId: '90451', tmName: 'Iván Marcone', tmPosition: 'Pivote' },
  'independiente|Kevin Lomónaco (CB)': { age: 24, tmId: '661136', tmName: 'Kevin Lomónaco', tmPosition: 'Defensa central' },
  'independiente|Leonardo Godoy (RB)': { age: 31, tmId: '369556', tmName: 'Leonardo Godoy', tmPosition: 'Lateral derecho' },
  'independiente|Matías Abaldo (LM)': { age: 22, tmId: '928647', tmName: 'Matías Abaldo', tmPosition: 'Extremo izquierdo' },
  'independiente|Rodrigo Rey (GK)': { age: 35, tmId: '166591', tmName: 'Rodrigo Rey', tmPosition: 'Portero' },
  'independiente|Santiago Arias (RB)': { age: 34, tmId: '120443', tmName: 'Santiago Arias', tmPosition: 'Lateral derecho' },
  'independiente|Santiago Montiel (RM)': { age: 25, tmId: '974336', tmName: 'Santiago Montiel', tmPosition: 'Extremo derecho' },
  'independiente|Sebastián Valdéz (CB)': { age: 30, tmId: '538374', tmName: 'Sebastián Valdez', tmPosition: 'Defensa central' },
  'instituto|Fernando Alarcón': { age: 32, tmId: '376853', tmName: 'Fernando Alarcón', tmPosition: 'Defensa central' },
  'instituto|Gastón Lodico': { age: 28, tmId: '563878', tmName: 'Gastón Lodico', tmPosition: 'Mediocentro' },
  'jaguares|Andrés Rentería': { age: 33, tmId: '233007', tmName: 'Andrés Rentería', tmPosition: 'Delantero centro' },
  'jaguares|Carlos Cantillo (CM)': { age: 23, tmId: '906651', tmName: 'Carlos Cantillo', tmPosition: 'Mediocentro' },
  'jaguares|Kahiser Lenis': { age: 25, tmId: '900540', tmName: 'Kahiser Lenis', tmPosition: 'Extremo izquierdo' },
  'junior|Cristian Barrios': { age: 28, tmId: '587296', tmName: 'Cristian Barrios', tmPosition: 'Extremo derecho' },
  'junior|Francisco Fydriszewski': { age: 33, tmId: '337921', tmName: 'Francisco Fydriszewski', tmPosition: 'Delantero centro' },
  'junior|Jean Pestaña': { age: 28, tmId: '572076', tmName: 'Jean Carlos Pestaña', tmPosition: 'Defensa central' },
  'junior|Luis Fernando Muriel': { age: 35, tmId: '119228', tmName: 'Luis Muriel', tmPosition: 'Delantero centro' },
  'junior|Mauro Silveira': { age: 26, tmId: '465682', tmName: 'Mauro Silveira', tmPosition: 'Portero' },
  'junior|Teófilo Gutiérrez': { age: 41, tmId: '77066', tmName: 'Teófilo Gutiérrez', tmPosition: 'Delantero centro' },
  'junior|Yimmi Chará': { age: 35, tmId: '165361', tmName: 'Yimmi Chará', tmPosition: 'Extremo derecho' },
  'lanus|Agustín Cardozo (CDM)': { age: 29, tmId: '469762', tmName: 'Agustín Cardozo', tmPosition: 'Pivote' },
  'lanus|Carlos Izquierdoz (CB)': { age: 37, tmId: '116968', tmName: 'Carlos Izquierdoz', tmPosition: 'Defensa central' },
  'lanus|Eduardo Salvio (RM)': { age: 36, tmId: '84535', tmName: 'Eduardo Salvio', tmPosition: 'Extremo derecho' },
  'lanus|Franco Petroli (GK)': { age: 28, tmId: '401587', tmName: 'Franco Petroli', tmPosition: 'Portero' },
  'lanus|José Canale (CB)': { age: 30, tmId: '402627', tmName: 'José Canale', tmPosition: 'Defensa central' },
  'lanus|Lucas Acosta (GK)': { age: 31, tmId: '296799', tmName: 'Lucas Acosta', tmPosition: 'Portero', currentClubName: 'Aldosivi' },
  'lanus|Marcelino Moreno (CAM)': { age: 31, tmId: '456617', tmName: 'Marcelino Moreno', tmPosition: 'Mediocentro ofensivo' },
  'lanus|Nahuel Losada (GK)': { age: 33, tmId: '323918', tmName: 'Nahuel Losada', tmPosition: 'Portero' },
  'lanus|Ramiro Carrera (LM)': { age: 32, tmId: '282283', tmName: 'Ramiro Carrera', tmPosition: 'Interior derecho' },
  'lanus|Sasha Marcich (LB)': { age: 28, tmId: '867621', tmName: 'Sasha Marcich', tmPosition: 'Lateral izquierdo' },
  'lanus|Walter Bou (ST)': { age: 32, tmId: '334233', tmName: 'Walter Bou', tmPosition: 'Delantero centro' },
  'llaneros_fc|Frank Castañeda (RM)': { age: 32, tmId: '562483', tmName: 'Frank Castañeda', tmPosition: 'Extremo izquierdo' },
  'los_andes|Brian Leizza (CB)': { age: 26, tmId: '752667', tmName: 'Brian Leizza', tmPosition: 'Defensa central' },
  'los_andes|Daniel Franco (CB)': { age: 35, tmId: '117115', tmName: 'Daniel Franco', tmPosition: 'Defensa central' },
  'los_andes|Gabriel Carrasco (RB)': { age: 29, tmId: '503005', tmName: 'Gabriel Carrasco', tmPosition: 'Lateral derecho' },
  'los_andes|Javier Bustillos (GK)': { age: 29, tmId: '537274', tmName: 'Javier Bustillos', tmPosition: 'Portero' },
  'los_andes|Juan Manuel Vázquez (LM)': { age: 32, tmId: '357330', tmName: 'Juan Manuel Vázquez', tmPosition: 'Mediocentro' },
  'los_andes|Julián Navas (RB)': { age: 32, tmId: '274970', tmName: 'Julián Navas', tmPosition: 'Lateral derecho' },
  'los_andes|Mario Galeano (ST)': { age: 24, tmId: '863400', tmName: 'Mario Galeano', tmPosition: 'Delantero centro' },
  'los_andes|Matías González (RM)': { age: 27, tmId: '985004', tmName: 'Matías González', tmPosition: 'Extremo derecho' },
  'los_andes|Mauricio Asenjo (ST)': { age: 32, tmId: '333762', tmName: 'Mauricio Asenjo', tmPosition: 'Delantero centro' },
  'los_andes|Sebastian López (GK)': { age: 40, tmId: '75444', tmName: 'Sebastián López', tmPosition: 'Portero' },
  'los_andes|Sergio Fabián Ortíz (CM)': { age: 25, tmId: '1034081', tmName: 'Sergio Ortíz', tmPosition: 'Mediocentro' },
  'medellin|Agustín Martegani': { age: 26, tmId: '732507', tmName: 'Agustín Martegani', tmPosition: 'Mediocentro ofensivo' },
  'medellin|Iván Arboleda': { age: 30, tmId: '260740', tmName: 'Iván Arboleda', tmPosition: 'Portero', currentClubName: 'Sarmiento' },
  'medellin|Jeison Medina': { age: 31, tmId: '570520', tmName: 'Jeison Medina', tmPosition: 'Delantero centro' },
  'medellin|Joaquín Varela (CB)': { age: 28, tmId: '421194', tmName: 'Joaquín Varela', tmPosition: 'Defensa central' },
  'medellin|Juan José Córdoba': { age: 23, tmId: '960057', tmName: 'Juan Córdoba', tmPosition: 'Extremo derecho' },
  'medellin|Salvador Ichazo': { age: 34, tmId: '131098', tmName: 'Salvador Ichazo', tmPosition: 'Portero' },
  'midland|Emilio Porro (RB)': { age: 30, tmId: '540460', tmName: 'Emilio Porro', tmPosition: 'Lateral derecho' },
  'midland|Fernando González (CB)': { age: 37, tmId: '124947', tmName: 'Fernando González', tmPosition: 'Defensa central', currentClubName: 'Agropecuario' },
  'midland|Genaro Cepeda (CB)': { age: 25, tmId: '996164', tmName: 'Genaro Cepeda', tmPosition: 'Defensa central' },
  'midland|Juan Cruz Vega (CAM)': { age: 28, tmId: '1307785', tmName: 'Juan Cruz Vega', tmPosition: 'Mediocentro ofensivo', currentClubName: 'Agropecuario' },
  'midland|Lautaro Díaz Laharque (RB)': { age: 30, tmId: '1204320', tmName: 'Lautaro Díaz Laharque', tmPosition: 'Lateral derecho' },
  'midland|Marcos Roseti (RM)': { age: 28, tmId: '888830', tmName: 'Marcos Roseti', tmPosition: 'Interior derecho' },
  'midland|Maximiliano Rogoski (CM)': { age: 32, tmId: '872121', tmName: 'Maximiliano Rogoski', tmPosition: 'Mediapunta', currentClubName: 'Nueva Chicago' },
  'midland|Pablo Casarico (CB)': { age: 25, tmId: '991810', tmName: 'Pablo Casarico', tmPosition: 'Defensa central' },
  'midland|Santino Primante (ST)': { age: 21, tmId: '1292332', tmName: 'Santino Primante', tmPosition: 'Delantero centro' },
  'millonarios|Andrey Estupiñán': { age: 32, tmId: '583812', tmName: 'Andrey Estupiñán', tmPosition: 'Extremo izquierdo' },
  'millonarios|Daniel Ruiz': { age: 25, tmId: '650833', tmName: 'Daniel Ruiz', tmPosition: 'Extremo izquierdo' },
  'millonarios|Darwin Quintero': { age: 38, tmId: '55666', tmName: 'Darwin Quintero', tmPosition: 'Mediocentro ofensivo' },
  'millonarios|James Aguirre': { age: 34, tmId: '332056', tmName: 'James Aguirre', tmPosition: 'Portero' },
  'millonarios|Álvaro Montero': { age: 31, tmId: '292985', tmName: 'Álvaro Montero', tmPosition: 'Portero', currentClubName: 'Boca Juniors' },
  'nacional|Edwin Cardona': { age: 33, tmId: '119342', tmName: 'Edwin Cardona', tmPosition: 'Mediocentro ofensivo' },
  'nacional|Elías Cabrera': { age: 23, tmId: '668513', tmName: 'Elías Cabrera', tmPosition: 'Mediocentro ofensivo', currentClubName: 'Tigre' },
  'nacional|Franco Armani': { age: 39, tmId: '119634', tmName: 'Franco Armani', tmPosition: 'Portero' },
  'nacional|Nicolás Rodríguez': { age: 22, tmId: '938123', tmName: 'Nicolás Rodríguez', tmPosition: 'Extremo derecho' },
  'nacional|William Tesillo': { age: 36, tmId: '137840', tmName: 'William Tesillo', tmPosition: 'Defensa central' },
  'newells|Armando Méndez': { age: 30, tmId: '605648', tmName: 'Armando Méndez', tmPosition: 'Lateral derecho' },
  'newells|Ever Banega': { age: 38, tmId: '12249', tmName: 'Éver Banega', tmPosition: 'Mediocentro', currentClubName: 'Defensa y Justicia' },
  'newells|Ian Glavinovich': { age: 24, tmId: '1027881', tmName: 'Ian Glavinovich', tmPosition: 'Defensa central' },
  'newells|Ignacio Ramírez': { age: 29, tmId: '402079', tmName: 'Ignacio Ramírez', tmPosition: 'Delantero centro' },
  'nueva_chicago|Alan Nahuel Ruiz (CAM)': { age: 32, tmId: '190442', tmName: 'Alan Ruiz', tmPosition: 'Mediocentro ofensivo' },
  'nueva_chicago|Bruno Palazzo (CB)': { age: 25, tmId: '847466', tmName: 'Bruno Palazzo', tmPosition: 'Lateral derecho' },
  'nueva_chicago|Dylan Gissi (CB)': { age: 35, tmId: '81056', tmName: 'Dylan Gissi', tmPosition: 'Defensa central' },
  'nueva_chicago|Emiliano Méndez (CDM)': { age: 37, tmId: '149478', tmName: 'Emiliano Méndez', tmPosition: 'Pivote' },
  'nueva_chicago|Gabriel Vega (CM)': { age: 24, tmId: '906749', tmName: 'Gabriel Vega', tmPosition: 'Mediocentro' },
  'nueva_chicago|Gonzalo Paz (CB)': { age: 33, tmId: '564972', tmName: 'Gonzalo Paz', tmPosition: 'Defensa central' },
  'nueva_chicago|Guillermo Ferracuti (LB)': { age: 35, tmId: '189203', tmName: 'Guillermo Ferracuti', tmPosition: 'Lateral izquierdo' },
  'nueva_chicago|Luciano Jachfe (GK)': { age: 25, tmId: '697852', tmName: 'Luciano Jachfe', tmPosition: 'Portero' },
  'nueva_chicago|Ramiro Balbuena (RM)': { age: 26, tmId: '833435', tmName: 'Ramiro Balbuena', tmPosition: 'Interior derecho' },
  'nueva_chicago|Sebastían Cocimano (ST)': { age: 26, tmId: '745326', tmName: 'Sebastián Cocimano', tmPosition: 'Delantero centro' },
  'once_caldas|Andrés Colorado (CDM)': { age: 27, tmId: '648309', tmName: 'Andrés Colorado', tmPosition: 'Pivote' },
  'once_caldas|Andrés Felipe Roa (CAM)': { age: 33, tmId: '304892', tmName: 'Andrés Roa', tmPosition: 'Mediocentro ofensivo' },
  'once_caldas|Dayro Moreno (ST)': { age: 40, tmId: '42457', tmName: 'Dayro Moreno', tmPosition: 'Delantero centro' },
  'once_caldas|Jaime Alvarado (CDM)': { age: 27, tmId: '522131', tmName: 'Jaime Alvarado', tmPosition: 'Pivote' },
  'once_caldas|Jeider Riquett (CB)': { age: 36, tmId: '462201', tmName: 'Jeider Riquett', tmPosition: 'Defensa central' },
  'once_caldas|Joan Parra': { age: 26, tmId: '610566', tmName: 'Joan Parra', tmPosition: 'Portero' },
  'once_caldas|Jorge Cardona (CB)': { age: 27, tmId: '628443', tmName: 'Jorge Cardona', tmPosition: 'Defensa central' },
  'once_caldas|Juan David Cuesta (RB)': { age: 28, tmId: '650822', tmName: 'Juan David Cuesta', tmPosition: 'Lateral derecho' },
  'once_caldas|Juan Nieto (CM)': { age: 33, tmId: '260391', tmName: 'Juan Pablo Nieto', tmPosition: 'Mediocentro' },
  'once_caldas|Michael Barrios (RM)': { age: 35, tmId: '313286', tmName: 'Michael Barrios', tmPosition: 'Extremo derecho' },
  'pasto|Diego Chavez (CM)': { age: 28, tmId: '841184', tmName: 'Diego Chávez', tmPosition: 'Mediocentro' },
  'pasto|Fáiner Torijano (CB)': { age: 37, tmId: '136005', tmName: 'Fáiner Torijano', tmPosition: 'Defensa central' },
  'pasto|Geovanni Banguera (GK)': { age: 30, tmId: '413558', tmName: 'Geovanni Banguera', tmPosition: 'Portero' },
  'pasto|Joider Micolta (LW)': { age: 24, tmId: '975151', tmName: 'Joider Micolta', tmPosition: 'Extremo izquierdo' },
  'pasto|Jorge Obregón (ST)': { age: 29, tmId: '414773', tmName: 'Jorge Obregón', tmPosition: 'Delantero centro' },
  'pasto|Julián Quiñónes (CB)': { age: 36, tmId: '203138', tmName: 'Julián Quiñónes', tmPosition: 'Defensa central' },
  'pasto|Mayer Gil': { age: 22, tmId: '827285', tmName: 'Mayer Gil', tmPosition: 'Extremo izquierdo' },
  'pasto|Nicolás Gil (CB)': { age: 29, tmId: '567347', tmName: 'Nicolás Gil', tmPosition: 'Defensa central' },
  'pasto|Santiago Córdoba (ST)': { age: 29, tmId: '670061', tmName: 'Santiago Córdoba', tmPosition: 'Delantero centro' },
  'pasto|Santiago Jiménez (RB)': { age: 28, tmId: '474678', tmName: 'Santiago Jiménez', tmPosition: 'Lateral derecho' },
  'pasto|Yéiler Góez (CM)': { age: 26, tmId: '585358', tmName: 'Yéiler Góez', tmPosition: 'Mediocentro' },
  'patronato|Federico Bravo (CDM)': { age: 32, tmId: '266775', tmName: 'Federico Bravo', tmPosition: 'Mediocentro' },
  'patronato|Fernando Evangelista (LB)': { age: 34, tmId: '240058', tmName: 'Fernando Evangelista', tmPosition: 'Defensa central' },
  'patronato|Fernando Moreyra (CB)': { age: 35, tmId: '563510', tmName: 'Fernando Moreyra', tmPosition: 'Defensa central' },
  'patronato|Franco Meritello (CB)': { age: 30, tmId: '840953', tmName: 'Franco Meritello', tmPosition: 'Defensa central' },
  'patronato|Franco Soldano (ST)': { age: 31, tmId: '358212', tmName: 'Franco Soldano', tmPosition: 'Delantero centro' },
  'patronato|Hernán Rivero (ST)': { age: 33, tmId: '418619', tmName: 'Hernán Rivero', tmPosition: 'Delantero centro' },
  'patronato|Marcos Enrique (CDM)': { age: 26, tmId: '742512', tmName: 'Marcos Enrique', tmPosition: 'Mediocentro', currentClubName: 'Tristán Suárez' },
  'patronato|Renzo Reynaga (ST)': { age: 27, tmId: '552509', tmName: 'Renzo Reynaga', tmPosition: 'Delantero centro' },
  'platense|Augusto Lotti (ST)': { age: 30, tmId: '406296', tmName: 'Augusto Lotti', tmPosition: 'Delantero centro' },
  'platense|Bautista Merlini (CAM)': { age: 31, tmId: '431737', tmName: 'Bautista Merlini', tmPosition: 'Extremo izquierdo' },
  'platense|Franco Zapiola (LM)': { age: 25, tmId: '909349', tmName: 'Franco Zapiola', tmPosition: 'Mediocentro ofensivo' },
  'platense|Guido Mainero (RM)': { age: 31, tmId: '441270', tmName: 'Guido Mainero', tmPosition: 'Extremo derecho' },
  'platense|Ignacio Vázquez (CB)': { age: 29, tmId: '552635', tmName: 'Ignacio Vázquez', tmPosition: 'Defensa central' },
  'platense|Juan Saborido (RB)': { age: 28, tmId: '866094', tmName: 'Juan Ignacio Saborido', tmPosition: 'Lateral derecho' },
  'platense|Leonardo Heredia (ST)': { age: 30, tmId: '538367', tmName: 'Leonardo Heredia', tmPosition: 'Mediocentro ofensivo' },
  'platense|Matías Borgogno (GK)': { age: 27, tmId: '592427', tmName: 'Matías Borgogno', tmPosition: 'Portero', currentClubName: 'Defensa y Justicia' },
  'platense|Maximiliano Amarfil (CM)': { age: 24, tmId: '990429', tmName: 'Maximiliano Amarfil', tmPosition: 'Pivote' },
  'platense|Víctor Cuesta (CB)': { age: 37, tmId: '104326', tmName: 'Victor Cuesta', tmPosition: 'Defensa central' },
  'racing|Adrián Martínez': { age: 34, tmId: '598769', tmName: 'Adrián Martínez', tmPosition: 'Delantero centro' },
  'racing|Alfonso Espino': { age: 34, tmId: '311044', tmName: 'Alfonso Espino', tmPosition: 'Lateral izquierdo' },
  'racing|Gabriel Arias': { age: 38, tmId: '54330', tmName: 'Gabriel Arias', tmPosition: 'Portero', currentClubName: 'Newells Old Boys' },
  'racing|Lautaro Díaz': { age: 28, tmId: '720294', tmName: 'Lautaro Díaz', tmPosition: 'Delantero centro' },
  'racing|Ulises Ortegoza': { age: 29, tmId: '654814', tmName: 'Ulises Ortegoza', tmPosition: 'Pivote' },
  'real_santander|Faiber Mendoza (CM)': { age: 25, tmId: '911030', tmName: 'Faiber Mendoza', tmPosition: 'Mediocentro' },
  'real_santander|Harlem Salas (LW)': { age: 26, tmId: '1077149', tmName: 'Harlem Salas', tmPosition: 'Extremo izquierdo' },
  'real_santander|Jordi Hernández (CB)': { age: 20, tmId: '1299626', tmName: 'Jordi Hernández' },
  'real_santander|José Torres': { age: 18, tmId: '1258246', tmName: 'José Torres' },
  'real_santander|Juan Ararat (RW)': { age: 23, tmId: '1234584', tmName: 'Juan Ararat', tmPosition: 'Extremo derecho' },
  'real_santander|Juan David Rueda (ST)': { age: 25, tmId: '907548', tmName: 'Juan David Rueda', tmPosition: 'Delantero centro' },
  'real_santander|Kevin Chacón (GK)': { age: 23, tmId: '983588', tmName: 'Kevin Chacón', tmPosition: 'Portero' },
  'real_santander|Rafael Tapia (ST)': { age: 26, tmId: '711141', tmName: 'Rafael Tapia', tmPosition: 'Extremo derecho' },
  'riestra|Ignacio Arce': { age: 34, tmId: '131206', tmName: 'Ignacio Arce', tmPosition: 'Portero' },
  'riestra|Jonathan Herrera': { age: 34, tmId: '485880', tmName: 'Jonathan Herrera', tmPosition: 'Delantero centro', currentClubName: 'Sarmiento' },
  'riestra|Milton Céliz': { age: 34, tmId: '260652', tmName: 'Milton Céliz', tmPosition: 'Mediocentro' },
  'river|Aníbal Moreno (CDM)': { age: 27, tmId: '642758', tmName: 'Aníbal Moreno', tmPosition: 'Pivote' },
  'river|Facundo Colidio (ST)': { age: 26, tmId: '491705', tmName: 'Facundo Colidio', tmPosition: 'Delantero centro' },
  'river|Fausto Vera (CM)': { age: 26, tmId: '491701', tmName: 'Fausto Vera', tmPosition: 'Pivote' },
  'river|Gonzalo Montiel (RB)': { age: 29, tmId: '402733', tmName: 'Gonzalo Montiel', tmPosition: 'Lateral derecho' },
  'river|Lucas Martínez Quarta (CB)': { age: 30, tmId: '373373', tmName: 'Lucas Martínez Quarta', tmPosition: 'Defensa central' },
  'river|Marcos Acuña (LB)': { age: 34, tmId: '60410', tmName: 'Marcos Acuña', tmPosition: 'Lateral izquierdo' },
  'river|Mauro Arambarri (CDM)': { age: 30, tmId: '290249', tmName: 'Mauro Arambarri', tmPosition: 'Mediocentro' },
  'river|Maximiliano Salas (ST)': { age: 28, tmId: '442231', tmName: 'Maximiliano Salas', tmPosition: 'Delantero centro' },
  'river|Nicolás Otamendi (CB)': { age: 38, tmId: '54781', tmName: 'Nicolás Otamendi', tmPosition: 'Defensa central' },
  'river|Sebastián Driussi (ST)': { age: 30, tmId: '294853', tmName: 'Sebastián Driussi', tmPosition: 'Delantero centro' },
  'river|Ángel Correa (CAM)': { age: 31, tmId: '266807', tmName: 'Ángel Correa', tmPosition: 'Mediapunta' },
  'rosario_central|Agustín Sández (LB)': { age: 25, tmId: '847023', tmName: 'Agustín Sández', tmPosition: 'Lateral izquierdo' },
  'rosario_central|Carlos Quintana (CB)': { age: 38, tmId: '54596', tmName: 'Carlos Quintana', tmPosition: 'Defensa central', currentClubName: 'Riestra' },
  'rosario_central|Conan Ledesma (GK)': { age: 33, tmId: '284342', tmName: 'Conan Ledesma', tmPosition: 'Portero' },
  'rosario_central|Emanuel Coronel (RB)': { age: 29, tmId: '565194', tmName: 'Emanuel Coronel', tmPosition: 'Lateral derecho' },
  'rosario_central|Facundo Mallo (CB)': { age: 31, tmId: '347193', tmName: 'Facundo Mallo', tmPosition: 'Defensa central' },
  'rosario_central|Federico Navarro (CDM)': { age: 26, tmId: '632131', tmName: 'Federico Navarro', tmPosition: 'Pivote' },
  'rosario_central|Franco Ibarra (CDM)': { age: 25, tmId: '741685', tmName: 'Franco Ibarra', tmPosition: 'Pivote' },
  'rosario_central|Jaminton Campaz (LM)': { age: 26, tmId: '491553', tmName: 'Jáminton Campaz', tmPosition: 'Extremo izquierdo' },
  'rosario_central|Pol Fernández (CM)': { age: 34, tmId: '220647', tmName: 'Pol Fernández', tmPosition: 'Mediocentro' },
  'rosario_central|Ángel Di María (RW)': { age: 38, tmId: '45320', tmName: 'Ángel Di María', tmPosition: 'Extremo derecho' },
  'san_lorenzo|Adam Bareiro': { age: 30, tmId: '514120', tmName: 'Adam Bareiro', tmPosition: 'Delantero centro', currentClubName: 'Boca Juniors' },
  'san_lorenzo|Gonzalo Ábrego': { age: 26, tmId: '836493', tmName: 'Gonzalo Abrego', tmPosition: 'Mediocentro' },
  'san_lorenzo|Nahuel Barrios': { age: 28, tmId: '503377', tmName: 'Nahuel Barrios', tmPosition: 'Extremo izquierdo' },
  'san_telmo|Elías Brítez (CM)': { age: 25, tmId: '1050567', tmName: 'Elías Brítez', tmPosition: 'Pivote' },
  'san_telmo|Emanuel Díaz (CB)': { age: 28, tmId: '871468', tmName: 'Emanuel Díaz', tmPosition: 'Defensa central' },
  'san_telmo|Fabián Henríquez (CM)': { age: 31, tmId: '400611', tmName: 'Fabián Henríquez', tmPosition: 'Pivote' },
  'san_telmo|Facundo Roncaglia (CB)': { age: 39, tmId: '61546', tmName: 'Facundo Roncaglia', tmPosition: 'Defensa central' },
  'san_telmo|Franco Tisera (ST)': { age: 36, tmId: '864739', tmName: 'Franco Tisera', tmPosition: 'Delantero centro', currentClubName: 'Los Andes' },
  'san_telmo|Gabriel Paredes (LB)': { age: 22, tmId: '1072990', tmName: 'Gabriel Paredes', tmPosition: 'Lateral izquierdo' },
  'san_telmo|Javier Iritier (LW)': { age: 31, tmId: '471654', tmName: 'Javier Iritier', tmPosition: 'Interior derecho' },
  'san_telmo|Juan Cruz Zurbriggen (ST)': { age: 26, tmId: '728222', tmName: 'Juan Cruz Zurbriggen', tmPosition: 'Delantero centro' },
  'san_telmo|Martín Batallini (ST)': { age: 34, tmId: '595986', tmName: 'Martín Batallini', tmPosition: 'Delantero centro' },
  'santafe|Franco Fagúndez': { age: 26, tmId: '929438', tmName: 'Franco Fagúndez', tmPosition: 'Mediapunta' },
  'santafe|Helibelton Palacios': { age: 33, tmId: '211389', tmName: 'Helibelton Palacios', tmPosition: 'Lateral derecho' },
  'santafe|Hugo Rodallega': { age: 41, tmId: '37934', tmName: 'Hugo Rodallega', tmPosition: 'Delantero centro' },
  'santafe|Kevin Balanta': { age: 29, tmId: '339758', tmName: 'Kevin Balanta', tmPosition: 'Defensa central' },
  'santafe|Luis Mario Palacios (LM)': { age: 25, tmId: '977739', tmName: 'Luis Palacios', tmPosition: 'Lateral derecho' },
  'sarmiento|Carlos Villalba (CM)': { age: 28, tmId: '652968', tmName: 'Carlos Villalba', tmPosition: 'Pivote' },
  'sarmiento|Cristian Zabala (CDM)': { age: 28, tmId: '613095', tmName: 'Cristian Zabala', tmPosition: 'Mediocentro' },
  'sarmiento|Gastón González (LM)': { age: 25, tmId: '689052', tmName: 'Gastón González', tmPosition: 'Extremo izquierdo' },
  'sarmiento|Javier Burrai (GK)': { age: 35, tmId: '223888', tmName: 'Javier Burrai', tmPosition: 'Portero', currentClubName: 'Millonarios FC' },
  'sarmiento|Jonatan Gómez (CM)': { age: 36, tmId: '84377', tmName: 'Jonatan Gómez', tmPosition: 'Mediocentro ofensivo' },
  'sarmiento|Juan Manuel Insaurralde (CB)': { age: 41, tmId: '65072', tmName: 'Juan Manuel Insaurralde', tmPosition: 'Defensa central' },
  'sarmiento|Junior Marabel (ST)': { age: 28, tmId: '567737', tmName: 'Junior Marabel', tmPosition: 'Delantero centro' },
  'sarmiento|Lucas Suárez (CB)': { age: 31, tmId: '322190', tmName: 'Lucas Suárez', tmPosition: 'Defensa central' },
  'sarmiento|Mauricio Martínez (CDM)': { age: 33, tmId: '309388', tmName: 'Mauricio Martínez', tmPosition: 'Pivote' },
  'sarmiento|Renzo Orihuela (CB)': { age: 25, tmId: '737892', tmName: 'Renzo Orihuela', tmPosition: 'Defensa central' },
  'sarmiento|Yair Arismendi (LB)': { age: 28, tmId: '440006', tmName: 'Yair Arismendi', tmPosition: 'Extremo izquierdo' },
  'temperley|Adrián Arregui (CDM)': { age: 33, tmId: '358016', tmName: 'Adrián Arregui', tmPosition: 'Pivote' },
  'temperley|Ezequiel Mastrolía (GK)': { age: 35, tmId: '159076', tmName: 'Ezequiel Mastrolía', tmPosition: 'Portero' },
  'temperley|Fernando Brandán (LM)': { age: 36, tmId: '358014', tmName: 'Fernando Brandán', tmPosition: 'Extremo derecho' },
  'temperley|Franco Díaz (CDM)': { age: 25, tmId: '748060', tmName: 'Franco Díaz', tmPosition: 'Mediocentro' },
  'temperley|Gabriel Esparza (LW)': { age: 33, tmId: '322115', tmName: 'Gabriel Esparza', tmPosition: 'Extremo izquierdo', currentClubName: 'A. Rafaela' },
  'temperley|Gabriel Hauche (CAM)': { age: 39, tmId: '54845', tmName: 'Gabriel Hauche', tmPosition: 'Delantero centro' },
  'temperley|Jerónimo Pourtau (GK)': { age: 26, tmId: '504885', tmName: 'Jerónimo Pourtau', tmPosition: 'Portero' },
  'temperley|Luciano Nieto (CAM)': { age: 35, tmId: '87455', tmName: 'Luciano Nieto', tmPosition: 'Mediocentro ofensivo' },
  'temperley|Pedro Souto (LB)': { age: 26, tmId: '924999', tmName: 'Pedro Souto', tmPosition: 'Lateral izquierdo' },
  'temperley|Santiago Flores (CB)': { age: 25, tmId: '1011266', tmName: 'Santiago Flores', tmPosition: 'Defensa central', currentClubName: 'Estudiantes de La Plata' },
  'tigres_fc|Camilo Ibarra (RW)': { age: 23, tmId: '1065723', tmName: 'Camilo Ibarra', tmPosition: 'Extremo derecho' },
  'tigres_fc|Duván Viáfara (CB)': { age: 27, tmId: '655425', tmName: 'Duván Viáfara', tmPosition: 'Defensa central' },
  'tigres_fc|Ghilbert Parra (LB)': { age: 24, tmId: '1105281', tmName: 'Ghilbert Parra', tmPosition: 'Lateral izquierdo' },
  'tigres_fc|Jesús Cano (LB)': { age: 28, tmId: '651475', tmName: 'Jesús Cano', tmPosition: 'Lateral izquierdo' },
  'tigres_fc|Matteo Frigerio (RW)': { age: 29, tmId: '850337', tmName: 'Matteo Frigerio', tmPosition: 'Extremo derecho' },
  'tigres_fc|Michael Mahecha (CM)': { age: 23, tmId: '1033121', tmName: 'Michael Mahecha', tmPosition: 'Mediocentro' },
  'tigres_fc|Orles Aragón (ST)': { age: 29, tmId: '572217', tmName: 'Orles Aragón', tmPosition: 'Delantero centro' },
  'tigres_fc|Ricardo Rosales (RB)': { age: 25, tmId: '885225', tmName: 'Ricardo Rosales', tmPosition: 'Lateral derecho' },
  'tigres_fc|Víctor Brid (GK)': { age: 25, tmId: '748802', tmName: 'Víctor Brid', tmPosition: 'Portero' },
  'tigre|Bruno Leyes (CDM)': { age: 24, tmId: '910641', tmName: 'Bruno Leyes', tmPosition: 'Pivote' },
  'tigre|David Romero (ST)': { age: 23, tmId: '668512', tmName: 'David Romero', tmPosition: 'Delantero centro' },
  'tigre|Felipe Zenobio (GK)': { age: 26, tmId: '826527', tmName: 'Felipe Zenobio', tmPosition: 'Portero' },
  'tigre|Gonzalo Martínez (CAM)': { age: 33, tmId: '281405', tmName: 'Gonzalo Martínez', tmPosition: 'Mediocentro ofensivo' },
  'tigre|Jabes Saralegui (RM)': { age: 23, tmId: '1174943', tmName: 'Jabes Saralegui', tmPosition: 'Mediocentro' },
  'tigre|Jalil Elías (CDM)': { age: 30, tmId: '376859', tmName: 'Jalil Elías', tmPosition: 'Pivote' },
  'tigre|Joaquín Laso (CB)': { age: 36, tmId: '360797', tmName: 'Joaquín Laso', tmPosition: 'Defensa central' },
  'tigre|Joaquín Mosqueira (CDM)': { age: 21, tmId: '1118712', tmName: 'Joaquín Mosqueira', tmPosition: 'Pivote' },
  'tigre|Nahuel Banegas (LB)': { age: 29, tmId: '697041', tmName: 'Nahuel Banegas', tmPosition: 'Lateral izquierdo' },
  'tigre|Sebastián Medina (LM)': { age: 26, tmId: '840774', tmName: 'Sebastián Medina', tmPosition: 'Interior izquierdo' },
  'tolima|Adrián Parra': { age: 29, tmId: '421011', tmName: 'Adrián Parra', tmPosition: 'Delantero centro' },
  'tolima|Anderson Angulo (CB)': { age: 30, tmId: '570531', tmName: 'Anderson Angulo', tmPosition: 'Defensa central' },
  'tolima|Brayan Rovira (CDM)': { age: 29, tmId: '345656', tmName: 'Brayan Rovira', tmPosition: 'Pivote' },
  'tolima|Jader Valencia (ST)': { age: 26, tmId: '570165', tmName: 'Jader Valencia', tmPosition: 'Delantero centro' },
  'tolima|Jan Ángulo (CB)': { age: 25, tmId: '1034026', tmName: 'Jan Ángulo', tmPosition: 'Defensa central' },
  'tolima|Jherson Mosquera (RB)': { age: 26, tmId: '638623', tmName: 'Jherson Mosquera', tmPosition: 'Lateral derecho' },
  'tolima|Junior Hernández (LB)': { age: 27, tmId: '746579', tmName: 'Junior Hernández', tmPosition: 'Lateral izquierdo' },
  'tolima|Luis Sandoval (ST)': { age: 27, tmId: '569222', tmName: 'Luis Sandoval', tmPosition: 'Delantero centro' },
  'tolima|Neto Volpi (GK)': { age: 33, tmId: '202959', tmName: 'Neto Volpi', tmPosition: 'Portero' },
  'tolima|Sebastián Guzmán (CDM)': { age: 29, tmId: '580422', tmName: 'Sebastián Guzmán', tmPosition: 'Pivote' },
  'tristan_suarez|Agustín Baldi (CB)': { age: 24, tmId: '697644', tmName: 'Agustin Baldi', tmPosition: 'Mediocentro' },
  'tristan_suarez|Alejandro Molina (RB)': { age: 28, tmId: '538529', tmName: 'Alejandro Molina', tmPosition: 'Lateral derecho' },
  'tristan_suarez|Diego Becker (LM)': { age: 28, tmId: '549603', tmName: 'Diego Becker', tmPosition: 'Interior izquierdo' },
  'tristan_suarez|Joaquín Bigo (GK)': { age: 28, tmId: '743023', tmName: 'Joaquin Bigo', tmPosition: 'Portero' },
  'tristan_suarez|Manuel Guillén (RB)': { age: 24, tmId: '985682', tmName: 'Manuel Guillén', tmPosition: 'Lateral derecho' },
  'tristan_suarez|Mauricio Manuel Guzmán (CB)': { age: 26, tmId: '756813', tmName: 'Mauricio Guzmán', tmPosition: 'Defensa central' },
  'tristan_suarez|Nicolás Del Priore (CM)': { age: 29, tmId: '613357', tmName: 'Nicolás Del Priore', tmPosition: 'Mediocentro' },
  'tristan_suarez|Nicolás Sánchez (LM)': { age: 34, tmId: '268846', tmName: 'Nicolás Sánchez', tmPosition: 'Mediocentro ofensivo' },
  'union_magdalena|Cristian Iguarán (ST)': { age: 21, tmId: '1258105', tmName: 'Cristian Iguarán' },
  'union_magdalena|Jimmy Congo (CDM)': { age: 28, tmId: '649794', tmName: 'Jimmy Congo', tmPosition: 'Pivote' },
  'union_magdalena|José Mercado (CM)': { age: 22, tmId: '1000701', tmName: 'José Mercado', tmPosition: 'Mediocentro' },
  'union_magdalena|José Palacios (RM)': { age: 29, tmId: '474620', tmName: 'José Palacios', tmPosition: 'Extremo izquierdo' },
  'union_magdalena|Juan Diego Giraldo (CM)': { age: 29, tmId: '474615', tmName: 'Juan Diego Giraldo', tmPosition: 'Mediocentro' },
  'union_magdalena|Juan Jose Vásquez (LB)': { age: 27, tmId: '904795', tmName: 'Juan Vásquez', tmPosition: 'Lateral izquierdo' },
  'union_magdalena|Víctor Cabezas (GK)': { age: 28, tmId: '463398', tmName: 'Víctor Cabezas', tmPosition: 'Portero' },
  'union_sf|Claudio Corvalán': { age: 37, tmId: '125108', tmName: 'Claudio Corvalán', tmPosition: 'Lateral izquierdo', currentClubName: 'Deportivo Madryn' },
  'union_sf|Lucas Gamba': { age: 39, tmId: '125906', tmName: 'Lucas Gamba', tmPosition: 'Delantero centro', currentClubName: 'Barracas Central' },
  'union_sf|Mauro Luna Diale': { age: 27, tmId: '653266', tmName: 'Mauro Luna Diale', tmPosition: 'Mediocentro ofensivo' },
  'velez|Claudio Baeza (CDM)': { age: 32, tmId: '248346', tmName: 'Claudio Baeza', tmPosition: 'Pivote' },
  'velez|Diego Valdés (CAM)': { age: 32, tmId: '249776', tmName: 'Diego Valdés', tmPosition: 'Mediocentro ofensivo' },
  'velez|Elías Gómez (LB)': { age: 32, tmId: '302139', tmName: 'Elías Gómez', tmPosition: 'Lateral izquierdo' },
  'velez|Emanuel Mammana (CB)': { age: 30, tmId: '275512', tmName: 'Emanuel Mammana', tmPosition: 'Defensa central' },
  'velez|Joaquín García (RB)': { age: 24, tmId: '829433', tmName: 'Joaquín García', tmPosition: 'Lateral derecho' },
  'velez|Manuel Lanzini (CAM)': { age: 33, tmId: '135853', tmName: 'Manuel Lanzini', tmPosition: 'Mediocentro ofensivo' },
  'velez|Matías Pellegrini (RM)': { age: 26, tmId: '606267', tmName: 'Matías Pellegrini', tmPosition: 'Extremo derecho' },
  'velez|Rodrigo Aliendro (CM)': { age: 35, tmId: '424045', tmName: 'Rodrigo Aliendro', tmPosition: 'Mediocentro' },
  'velez|Tomás Marchiori (GK)': { age: 31, tmId: '596909', tmName: 'Tomás Marchiori', tmPosition: 'Portero' },
  'villa_mitre|Enzo González (CDM)': { age: 25, tmId: '1279914', tmName: 'Enzo González', tmPosition: 'Mediapunta', currentClubName: 'Defensores de Belgrano' },
  'villa_mitre|Leandro Fernández (LM)': { age: 35, tmId: '131840', tmName: 'Leandro Fernández', tmPosition: 'Extremo izquierdo', currentClubName: 'Defensa y Justicia' },
};
